<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       

        $countries = [
            ["name" => "Afeganistão", "continent_id" => 6],
            ["name" => "África do Sul", "continent_id" => 7],
            ["name" => "Albânia", "continent_id" => 1],
            ["name" => "Alemanha", "continent_id" => 1],
            ["name" => "Andorra", "continent_id" => 1],
            ["name" => "Angola", "continent_id" => 7],
            ["name" => "Antígua e Barbuda", "continent_id" => 2],
            ["name" => "Arábia Saudita", "continent_id" => 6],
            ["name" => "Argélia", "continent_id" => 7],
            ["name" => "Argentina", "continent_id" => 2],
            ["name" => "Armênia", "continent_id" => 6],
            ["name" => "Austrália", "continent_id" => 5],
            ["name" => "Áustria", "continent_id" => 1],
            ["name" => "Azerbaijão", "continent_id" => 6],
            ["name" => "Bahamas", "continent_id" => 4],
            ["name" => "Bahrein", "continent_id" => 6],
            ["name" => "Bangladesh", "continent_id" => 6],
            ["name" => "Barbados", "continent_id" => 2],
            ["name" => "Belarus", "continent_id" => 1],
            ["name" => "Bélgica", "continent_id" => 1],
            ["name" => "Belize", "continent_id" => 4],
            ["name" => "Benin", "continent_id" => 7],
            ["name" => "Bolívia", "continent_id" => 2],
            ["name" => "Bósnia e Herzegovina", "continent_id" => 1],
            ["name" => "Botsuana", "continent_id" => 7],
            ["name" => "Brasil", "continent_id" => 2],
            ["name" => "Brunei", "continent_id" => 6],
            ["name" => "Bulgária", "continent_id" => 1],
            ["name" => "Burkina Faso", "continent_id" => 7],
            ["name" => "Burundi", "continent_id" => 7],
            ["name" => "Butão", "continent_id" => 6],
            ["name" => "Cabo Verde", "continent_id" => 7],
            ["name" => "Camarões", "continent_id" => 7],
            ["name" => "Camboja", "continent_id" => 6],
            ["name" => "Canadá", "continent_id" => 3],
            ["name" => "Catar", "continent_id" => 6],
            ["name" => "Cazaquistão", "continent_id" => 6],
            ["name" => "Chade", "continent_id" => 7],
            ["name" => "Chile", "continent_id" => 2],
            ["name" => "China", "continent_id" => 6],
            ["name" => "Chipre", "continent_id" => 1],
            ["name" => "Colômbia", "continent_id" => 2],
            ["name" => "Comores", "continent_id" => 7],
            ["name" => "Congo", "continent_id" => 7],
            ["name" => "Costa do Marfim", "continent_id" => 7],
            ["name" => "Costa Rica", "continent_id" => 3],
            ["name" => "Croácia", "continent_id" => 1],
            ["name" => "Cuba", "continent_id" => 2],
            ["name" => "Dinamarca", "continent_id" => 1],
            ["name" => "Djibouti", "continent_id" => 7],
            ["name" => "Dominica", "continent_id" => 2],
            ["name" => "Egito", "continent_id" => 7],
            ["name" => "Emirados Árabes Unidos", "continent_id" => 6],
            ["name" => "Equador", "continent_id" => 2],
            ["name" => "Eritreia", "continent_id" => 7],
            ["name" => "Eslováquia", "continent_id" => 1],
            ["name" => "Eslovênia", "continent_id" => 1],
            ["name" => "Espanha", "continent_id" => 1],
            ["name" => "Estados Unidos", "continent_id" => 3],
            ["name" => "Estônia", "continent_id" => 1],
            ["name" => "Eswatini", "continent_id" => 7],
            ["name" => "Etiópia", "continent_id" => 7],
            ["name" => "Fiji", "continent_id" => 5],
            ["name" => "Filipinas", "continent_id" => 6],
            ["name" => "Finlândia", "continent_id" => 1],
            ["name" => "França", "continent_id" => 1],
            ["name" => "Gabão", "continent_id" => 7],
            ["name" => "Gâmbia", "continent_id" => 7],
            ["name" => "Geórgia", "continent_id" => 1],
            ["name" => "Gana", "continent_id" => 7],
            ["name" => "Grécia", "continent_id" => 1],
            ["name" => "Granada", "continent_id" => 2],
            ["name" => "Guatemala", "continent_id" => 4],
            ["name" => "Guiana", "continent_id" => 2],
            ["name" => "Guiné", "continent_id" => 7],
            ["name" => "Guiné Equatorial", "continent_id" => 7],
            ["name" => "Guiné-Bissau", "continent_id" => 7],
            ["name" => "Haiti", "continent_id" => 2],
            ["name" => "Holanda", "continent_id" => 1],
            ["name" => "Honduras", "continent_id" => 4],
            ["name" => "Hungria", "continent_id" => 1],
            ["name" => "Iémen", "continent_id" => 6],
            ["name" => "Ilhas Marshall", "continent_id" => 5],
            ["name" => "Ilhas Salomão", "continent_id" => 5],
            ["name" => "Índia", "continent_id" => 6],
            ["name" => "Indonésia", "continent_id" => 6],
            ["name" => "Irã", "continent_id" => 6],
            ["name" => "Iraque", "continent_id" => 6],
            ["name" => "Irlanda", "continent_id" => 1],
            ["name" => "Islândia", "continent_id" => 1],
            ["name" => "Israel", "continent_id" => 6],
            ["name" => "Itália", "continent_id" => 1],
            ["name" => "Jamaica", "continent_id" => 2],
            ["name" => "Japão", "continent_id" => 6],
            ["name" => "Jordânia", "continent_id" => 6],
            ["name" => "Kiribati", "continent_id" => 5],
            ["name" => "Kuwait", "continent_id" => 6],
            ["name" => "Laos", "continent_id" => 6],
            ["name" => "Lesoto", "continent_id" => 7],
            ["name" => "Letônia", "continent_id" => 1],
            ["name" => "Líbano", "continent_id" => 6],
            ["name" => "Libéria", "continent_id" => 7],
            ["name" => "Líbia", "continent_id" => 7],
            ["name" => "Liechtenstein", "continent_id" => 1],
            ["name" => "Lituânia", "continent_id" => 1],
            ["name" => "Luxemburgo", "continent_id" => 1],
            ["name" => "Macedônia do Norte", "continent_id" => 1],
            ["name" => "Madagáscar", "continent_id" => 7],
            ["name" => "Malásia", "continent_id" => 6],
            ["name" => "Malaui", "continent_id" => 7],
            ["name" => "Maldivas", "continent_id" => 6],
            ["name" => "Mali", "continent_id" => 7],
            ["name" => "Malta", "continent_id" => 1],
            ["name" => "Marrocos", "continent_id" => 7],
            ["name" => "Maurícia", "continent_id" => 7],
            ["name" => "Mauritânia", "continent_id" => 7],
            ["name" => "México", "continent_id" => 3],
            ["name" => "Micronésia", "continent_id" => 5],
            ["name" => "Moçambique", "continent_id" => 7],
            ["name" => "Moldávia", "continent_id" => 1],
            ["name" => "Mônaco", "continent_id" => 1],
            ["name" => "Mongólia", "continent_id" => 6],
            ["name" => "Montenegro", "continent_id" => 1],
            ["name" => "Namíbia", "continent_id" => 7],
            ["name" => "Nauru", "continent_id" => 5],
            ["name" => "Nepal", "continent_id" => 6],
            ["name" => "Nicarágua", "continent_id" => 4],
            ["name" => "Níger", "continent_id" => 7],
            ["name" => "Nigéria", "continent_id" => 7],
            ["name" => "Noruega", "continent_id" => 1],
            ["name" => "Nova Zelândia", "continent_id" => 5],
            ["name" => "Omã", "continent_id" => 6],
            ["name" => "Palau", "continent_id" => 5],
            ["name" => "Panamá", "continent_id" => 4],
            ["name" => "Papua Nova Guiné", "continent_id" => 5],
            ["name" => "Paquistão", "continent_id" => 6],
            ["name" => "Paraguai", "continent_id" => 2],
            ["name" => "Peru", "continent_id" => 2],
            ["name" => "Polônia", "continent_id" => 1],
            ["name" => "Portugal", "continent_id" => 1],
            ["name" => "Quênia", "continent_id" => 7],
            ["name" => "Quirguistão", "continent_id" => 6],
            ["name" => "Reino Unido", "continent_id" => 1],
            ["name" => "República Centro-Africana", "continent_id" => 7],
            ["name" => "República Checa", "continent_id" => 1],
            ["name" => "República Democrática do Congo", "continent_id" => 7],
            ["name" => "República Dominicana", "continent_id" => 4],
            ["name" => "Romênia", "continent_id" => 1],
            ["name" => "Ruanda", "continent_id" => 7],
            ["name" => "Rússia", "continent_id" => 1],
            ["name" => "Saara Ocidental", "continent_id" => 7],
            ["name" => "Salvador", "continent_id" => 4],
            ["name" => "Samoa", "continent_id" => 5],
            ["name" => "Santa Lúcia", "continent_id" => 2],
            ["name" => "São Cristóvão e Nevis", "continent_id" => 2],
            ["name" => "São Marinho", "continent_id" => 1],
            ["name" => "São Tomé e Príncipe", "continent_id" => 7],
            ["name" => "São Vicente e Granadinas", "continent_id" => 2],
            ["name" => "Senegal", "continent_id" => 7],
            ["name" => "Serra Leoa", "continent_id" => 7],
            ["name" => "Sérvia", "continent_id" => 1],
            ["name" => "Síria", "continent_id" => 6],
            ["name" => "Somália", "continent_id" => 7],
            ["name" => "Sri Lanka", "continent_id" => 6],
            ["name" => "Suazilândia", "continent_id" => 7],
            ["name" => "Sudão", "continent_id" => 7],
            ["name" => "Sudão do Sul", "continent_id" => 7],
            ["name" => "Suécia", "continent_id" => 1],
            ["name" => "Suíça", "continent_id" => 1],
            ["name" => "Suriname", "continent_id" => 2],
            ["name" => "Tailândia", "continent_id" => 6],
            ["name" => "Taiwan", "continent_id" => 6],
            ["name" => "Tajiquistão", "continent_id" => 6],
            ["name" => "Tanzânia", "continent_id" => 7],
            ["name" => "Timor-Leste", "continent_id" => 6],
            ["name" => "Togo", "continent_id" => 7],
            ["name" => "Tonga", "continent_id" => 5],
            ["name" => "Trinidad e Tobago", "continent_id" => 2],
            ["name" => "Tunísia", "continent_id" => 7],
            ["name" => "Turcomenistão", "continent_id" => 6],
            ["name" => "Turquia", "continent_id" => 6],
            ["name" => "Tuvalu", "continent_id" => 5],
            ["name" => "Ucrânia", "continent_id" => 1],
            ["name" => "Uganda", "continent_id" => 7],
            ["name" => "Uruguai", "continent_id" => 2],
            ["name" => "Uzbequistão", "continent_id" => 6],
            ["name" => "Vanuatu", "continent_id" => 5],
            ["name" => "Vaticano", "continent_id" => 1],
            ["name" => "Venezuela", "continent_id" => 2],
            ["name" => "Vietnã", "continent_id" => 6],
            ["name" => "Zâmbia", "continent_id" => 7],
            ["name" => "Zimbábue", "continent_id" => 7],
        ];

        foreach($countries as $country) {
            Country::create([
                'name' => $country['name'],
                'continent_id' => $country['continent_id']
            ]);
        }
    }
}
